# NumPy Hands-On Tutorial

A comprehensive guide to NumPy for data handling and processing with executable examples.

In [2]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import time
print("Setup complete!")


Setup complete!


## 1. Getting Started

In [3]:
# Check NumPy version
print(f"NumPy version: {np.__version__}")


NumPy version: 2.0.2


In [4]:
# Speed comparison: Python list vs NumPy array
size = 1_000_000

# Create a Python list
python_list = list(range(size))

# Create a NumPy array
numpy_array = np.arange(size)

# Time Python list operation
start = time.time()
for _ in range(100):
    result = [x * 2 for x in python_list]
python_time = time.time() - start

# Time NumPy array operation
start = time.time()
for _ in range(100):
    result = numpy_array * 2
numpy_time = time.time() - start

print(f"Python list time: {python_time:.4f} seconds")
print(f"NumPy array time: {numpy_time:.4f} seconds")
print(f"Speedup: {python_time / numpy_time:.1f}x faster with NumPy")


Python list time: 2.4855 seconds
NumPy array time: 0.0342 seconds
Speedup: 72.8x faster with NumPy


## 2. Creating Arrays

In [5]:
# Creating arrays from Python lists
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array:", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:")
print(arr_2d)

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D array shape:", arr_3d.shape)


1D array: [1 2 3 4 5]
2D array:
[[1 2 3]
 [4 5 6]]
3D array shape: (2, 2, 2)


In [6]:
# Creating arrays with special values
zeros_arr = np.zeros((3, 4))
print("Zeros array:")
print(zeros_arr)

ones_arr = np.ones((2, 3))
print("Ones array:")
print(ones_arr)

full_arr = np.full((2, 3), 7)
print("Full array (filled with 7):")
print(full_arr)


Zeros array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array:
[[1. 1. 1.]
 [1. 1. 1.]]
Full array (filled with 7):
[[7 7 7]
 [7 7 7]]


In [7]:
# Identity and empty arrays
eye_arr = np.eye(4)
print("Identity matrix:")
print(eye_arr)

empty_arr = np.empty((2, 2))
print("Empty array (uninitialized):")
print(empty_arr)


Identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Empty array (uninitialized):
[[1. 1.]
 [1. 1.]]


In [8]:
# arange - similar to Python range
arr_arange = np.arange(0, 10, 2)
print("arange(0, 10, 2):", arr_arange)

# linspace - create evenly spaced values
arr_linspace = np.linspace(0, 10, 5)
print("linspace(0, 10, 5):", arr_linspace)

# logspace - logarithmically spaced
arr_logspace = np.logspace(0, 2, 4)
print("logspace(0, 2, 4):", arr_logspace)


arange(0, 10, 2): [0 2 4 6 8]
linspace(0, 10, 5): [ 0.   2.5  5.   7.5 10. ]
logspace(0, 2, 4): [  1.           4.64158883  21.5443469  100.        ]


In [9]:
# Specifying data types
arr_int = np.array([1, 2, 3], dtype=np.int32)
print("Int32 array:", arr_int, "dtype:", arr_int.dtype)

arr_float = np.array([1, 2, 3], dtype=np.float64)
print("Float64 array:", arr_float, "dtype:", arr_float.dtype)

arr_complex = np.array([1+2j, 3+4j], dtype=np.complex128)
print("Complex array:", arr_complex, "dtype:", arr_complex.dtype)


Int32 array: [1 2 3] dtype: int32
Float64 array: [1. 2. 3.] dtype: float64
Complex array: [1.+2.j 3.+4.j] dtype: complex128


In [10]:
# fromfunction - create array using a function
def func(i, j):
    return i * j

arr_fromfunc = np.fromfunction(func, (5, 5))
print("Array from function (i*j):")
print(arr_fromfunc.astype(int))


Array from function (i*j):
[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]]


## 3. Array Properties

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Array:")
print(arr)
print(f"ndim (number of dimensions): {arr.ndim}")
print(f"shape: {arr.shape}")
print(f"size (total elements): {arr.size}")
print(f"dtype: {arr.dtype}")
print(f"itemsize (bytes per element): {arr.itemsize}")
print(f"nbytes (total bytes): {arr.nbytes}")


Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim (number of dimensions): 2
shape: (3, 3)
size (total elements): 9
dtype: int64
itemsize (bytes per element): 8
nbytes (total bytes): 72


## 4. Indexing & Slicing

In [12]:
# 1D indexing
arr_1d = np.array([10, 20, 30, 40, 50])
print("Array:", arr_1d)
print(f"Index 0: {arr_1d[0]}")
print(f"Index -1 (last): {arr_1d[-1]}")
print(f"Index 2: {arr_1d[2]}")


Array: [10 20 30 40 50]
Index 0: 10
Index -1 (last): 50
Index 2: 30


In [13]:
# 1D slicing
arr_1d = np.array([10, 20, 30, 40, 50])
print("Array:", arr_1d)
print("arr_1d[1:4]:", arr_1d[1:4])
print("arr_1d[:3]:", arr_1d[:3])
print("arr_1d[::2]:", arr_1d[::2])
print("Reverse arr_1d[::-1]:", arr_1d[::-1])


Array: [10 20 30 40 50]
arr_1d[1:4]: [20 30 40]
arr_1d[:3]: [10 20 30]
arr_1d[::2]: [10 30 50]
Reverse arr_1d[::-1]: [50 40 30 20 10]


In [14]:
# 2D indexing
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array:")
print(arr_2d)
print(f"arr_2d[0, 0]: {arr_2d[0, 0]}")
print(f"arr_2d[1, 2]: {arr_2d[1, 2]}")
print(f"arr_2d[-1, -1]: {arr_2d[-1, -1]}")


Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr_2d[0, 0]: 1
arr_2d[1, 2]: 6
arr_2d[-1, -1]: 9


In [15]:
# 2D slicing
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Full array:")
print(arr_2d)
print("arr_2d[0, :]:", arr_2d[0, :])  # First row
print("arr_2d[:, 1]:", arr_2d[:, 1])  # Second column
print("arr_2d[1:3, 0:2]:")
print(arr_2d[1:3, 0:2])  # Submatrix


Full array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr_2d[0, :]: [1 2 3]
arr_2d[:, 1]: [2 5 8]
arr_2d[1:3, 0:2]:
[[4 5]
 [7 8]]


In [16]:
# Views vs Copies
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)

# Create a view (shares data)
view = arr[1:4]
view[0] = 999
print("After modifying view, original array:", arr)

# Create a copy (independent)
arr = np.array([1, 2, 3, 4, 5])
copy = arr[1:4].copy()
copy[0] = 999
print("After modifying copy, original array:", arr)


Original array: [1 2 3 4 5]
After modifying view, original array: [  1 999   3   4   5]
After modifying copy, original array: [1 2 3 4 5]


## 5. Reshaping & Stacking

In [17]:
# reshape
arr = np.arange(12)
print("Original shape:", arr.shape)
print("Original:", arr)

reshaped = arr.reshape(3, 4)
print("Reshaped (3, 4):")
print(reshaped)

reshaped = arr.reshape(2, 2, 3)
print("Reshaped (2, 2, 3) shape:", reshaped.shape)


Original shape: (12,)
Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped (3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped (2, 2, 3) shape: (2, 2, 3)


In [18]:
# reshape with -1 (automatic dimension)
arr = np.arange(12)
print("Original shape:", arr.shape)

reshaped = arr.reshape(3, -1)
print("Reshaped (3, -1):")
print(reshaped)

reshaped = arr.reshape(-1, 1)
print("Reshaped (-1, 1) shape:", reshaped.shape)


Original shape: (12,)
Reshaped (3, -1):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped (-1, 1) shape: (12, 1)


In [19]:
# transpose
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original:")
print(arr)
print("Transposed:")
print(arr.T)


Original:
[[1 2 3]
 [4 5 6]]
Transposed:
[[1 4]
 [2 5]
 [3 6]]


In [20]:
# newaxis and expand_dims
arr = np.array([1, 2, 3])
print("Original shape:", arr.shape)

# Add axis at position 0
arr_expanded = arr[np.newaxis, :]
print("After arr[np.newaxis, :] shape:", arr_expanded.shape)

# Add axis at position 1
arr_expanded = arr[:, np.newaxis]
print("After arr[:, np.newaxis] shape:", arr_expanded.shape)

# Using expand_dims
arr_expanded = np.expand_dims(arr, axis=0)
print("After expand_dims(arr, axis=0) shape:", arr_expanded.shape)


Original shape: (3,)
After arr[np.newaxis, :] shape: (1, 3)
After arr[:, np.newaxis] shape: (3, 1)
After expand_dims(arr, axis=0) shape: (1, 3)


In [21]:
# squeeze - remove dimensions of size 1
arr = np.array([[[1], [2], [3]]])
print("Original shape:", arr.shape)

squeezed = np.squeeze(arr)
print("After squeeze shape:", squeezed.shape)


Original shape: (1, 3, 1)
After squeeze shape: (3,)


In [22]:
# vstack and hstack
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6]])

print("arr1:")
print(arr1)
print("arr2:")
print(arr2)
print("vstack:")
print(np.vstack([arr1, arr2]))
print("hstack:")
print(np.hstack([arr1, arr2]))


arr1:
[[1 2 3]]
arr2:
[[4 5 6]]
vstack:
[[1 2 3]
 [4 5 6]]
hstack:
[[1 2 3 4 5 6]]


In [23]:
# column_stack and concatenate
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("arr1:", arr1)
print("arr2:", arr2)
print("column_stack:")
print(np.column_stack([arr1, arr2]))

# concatenate along axis
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
print("concatenate along axis=0:")
print(np.concatenate([arr1, arr2], axis=0))


arr1: [1 2 3]
arr2: [4 5 6]
column_stack:
[[1 4]
 [2 5]
 [3 6]]
concatenate along axis=0:
[[1 2]
 [3 4]
 [5 6]]


In [24]:
# split
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Original array:")
print(arr)

split_arrs = np.split(arr, 2, axis=1)
print("Split along axis 1:")
for i, a in enumerate(split_arrs):
    print(f"  Part {i}:")
    print(a)


Original array:
[[1 2 3 4]
 [5 6 7 8]]
Split along axis 1:
  Part 0:
[[1 2]
 [5 6]]
  Part 1:
[[3 4]
 [7 8]]


## 6. Math Operations

In [25]:
# Element-wise arithmetic
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("a:", a)
print("b:", b)
print("a + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("b / a:", b / a)
print("a ** 2:", a ** 2)
print("a % 3:", a % 3)


a: [1 2 3 4]
b: [10 20 30 40]
a + b: [11 22 33 44]
a - b: [ -9 -18 -27 -36]
a * b: [ 10  40  90 160]
b / a: [10. 10. 10. 10.]
a ** 2: [ 1  4  9 16]
a % 3: [1 2 0 1]


In [26]:
# Math functions
arr = np.array([1, 4, 9, 16, 25])
print("Array:", arr)
print("sqrt:", np.sqrt(arr))

arr = np.array([0, 1, 2])
print("exp:", np.exp(arr))
print("log (of [1, 2.718, 7.389]):", np.log(np.exp(arr)))

arr = np.array([-3, -1, 0, 1, 3])
print("abs:", np.abs(arr))
print("round(np.sqrt([2, 3, 5])):", np.round(np.sqrt(np.array([2, 3, 5]))))


Array: [ 1  4  9 16 25]
sqrt: [1. 2. 3. 4. 5.]
exp: [1.         2.71828183 7.3890561 ]
log (of [1, 2.718, 7.389]): [0. 1. 2.]
abs: [3 1 0 1 3]
round(np.sqrt([2, 3, 5])): [1. 2. 2.]


In [27]:
# Comparison operations return boolean arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 2, 3, 5, 1])

print("a:", a)
print("b:", b)
print("a == b:", a == b)
print("a > b:", a > b)
print("a <= 3:", a <= 3)


a: [1 2 3 4 5]
b: [3 2 3 5 1]
a == b: [False  True  True False False]
a > b: [False False False False  True]
a <= 3: [ True  True  True False False]


In [28]:
# Trigonometric functions
angles = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])
print("Angles (radians):", angles)
print("sin:", np.sin(angles))
print("cos:", np.cos(angles))
print("tan:", np.tan(angles[:4]))


Angles (radians): [0.         0.52359878 0.78539816 1.04719755 1.57079633]
sin: [0.         0.5        0.70710678 0.8660254  1.        ]
cos: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tan: [0.         0.57735027 1.         1.73205081]


In [29]:
# clip, maximum, minimum
arr = np.array([-5, -2, 0, 3, 8, 12])
print("Array:", arr)
print("clip(arr, -2, 5):", np.clip(arr, -2, 5))

a = np.array([1, 5, 3])
b = np.array([2, 2, 8])
print("a:", a)
print("b:", b)
print("maximum:", np.maximum(a, b))
print("minimum:", np.minimum(a, b))


Array: [-5 -2  0  3  8 12]
clip(arr, -2, 5): [-2 -2  0  3  5  5]
a: [1 5 3]
b: [2 2 8]
maximum: [2 5 8]
minimum: [1 2 3]


## 7. Broadcasting

In [30]:
# Scalar + array
arr = np.array([1, 2, 3, 4])
scalar = 10
print("Array:", arr)
print("Scalar:", scalar)
print("Array + Scalar:", arr + scalar)
print("Array * Scalar:", arr * scalar)


Array: [1 2 3 4]
Scalar: 10
Array + Scalar: [11 12 13 14]
Array * Scalar: [10 20 30 40]


In [31]:
# 1D + 2D broadcasting
arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[10, 20, 30], [40, 50, 60]])

print("1D array:", arr_1d)
print("2D array:")
print(arr_2d)
print("2D + 1D:")
print(arr_2d + arr_1d)


1D array: [1 2 3]
2D array:
[[10 20 30]
 [40 50 60]]
2D + 1D:
[[11 22 33]
 [41 52 63]]


In [32]:
# Broadcasting example: normalize columns
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
print("Original data:")
print(data)

# Compute mean of each column
column_means = data.mean(axis=0)
print("Column means:", column_means)

# Subtract means (broadcasting)
normalized = data - column_means
print("Normalized data:")
print(normalized)
print("Column means after normalization:", normalized.mean(axis=0))


Original data:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Column means: [4. 5. 6.]
Normalized data:
[[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]
Column means after normalization: [0. 0. 0.]


## 8. Aggregation & Statistics

In [33]:
# Global aggregation
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)
print("sum:", arr.sum())
print("mean:", arr.mean())
print("std (standard deviation):", arr.std())
print("var (variance):", arr.var())
print("min:", arr.min())
print("max:", arr.max())


Array: [1 2 3 4 5]
sum: 15
mean: 3.0
std (standard deviation): 1.4142135623730951
var (variance): 2.0
min: 1
max: 5


In [34]:
# Aggregation along axis
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array:")
print(arr_2d)
print("sum(axis=0) - column sums:", arr_2d.sum(axis=0))
print("sum(axis=1) - row sums:", arr_2d.sum(axis=1))
print("mean(axis=0):", arr_2d.mean(axis=0))
print("mean(axis=1):", arr_2d.mean(axis=1))


Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
sum(axis=0) - column sums: [12 15 18]
sum(axis=1) - row sums: [ 6 15 24]
mean(axis=0): [4. 5. 6.]
mean(axis=1): [2. 5. 8.]


In [35]:
# cumsum and cumprod
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)
print("cumsum:", np.cumsum(arr))
print("cumprod:", np.cumprod(arr))


Array: [1 2 3 4 5]
cumsum: [ 1  3  6 10 15]
cumprod: [  1   2   6  24 120]


In [36]:
# argmin and argmax
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Array:", arr)
print("argmin (index of min):", np.argmin(arr))
print("argmax (index of max):", np.argmax(arr))
print("min value:", arr[np.argmin(arr)])
print("max value:", arr[np.argmax(arr)])


Array: [3 1 4 1 5 9 2 6]
argmin (index of min): 1
argmax (index of max): 5
min value: 1
max value: 9


In [37]:
# Percentiles and quantiles
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Array:", arr)
print("25th percentile:", np.percentile(arr, 25))
print("50th percentile (median):", np.percentile(arr, 50))
print("75th percentile:", np.percentile(arr, 75))
print("quantile(0.25):", np.quantile(arr, 0.25))


Array: [ 1  2  3  4  5  6  7  8  9 10]
25th percentile: 3.25
50th percentile (median): 5.5
75th percentile: 7.75
quantile(0.25): 3.25


In [38]:
# Correlation and covariance
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 4, 6])
print("x:", x)
print("y:", y)
print("correlation coefficient:", np.corrcoef(x, y)[0, 1])
print("covariance matrix:")
print(np.cov(x, y))


x: [1 2 3 4 5]
y: [2 4 5 4 6]
correlation coefficient: 0.8528028654224418
covariance matrix:
[[2.5 2. ]
 [2.  2.2]]


## 9. Boolean Masking & Fancy Indexing

In [39]:
# Boolean mask creation
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mask = arr > 5
print("Array:", arr)
print("Mask (arr > 5):", mask)
print("Filtered array:", arr[mask])


Array: [ 1  2  3  4  5  6  7  8  9 10]
Mask (arr > 5): [False False False False False  True  True  True  True  True]
Filtered array: [ 6  7  8  9 10]


In [40]:
# Complex boolean conditions
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mask = (arr > 3) & (arr < 8)
print("Array:", arr)
print("Mask ((arr > 3) & (arr < 8)):", mask)
print("Filtered:", arr[mask])

mask = (arr < 3) | (arr > 8)
print("Mask ((arr < 3) | (arr > 8)):", mask)
print("Filtered:", arr[mask])


Array: [ 1  2  3  4  5  6  7  8  9 10]
Mask ((arr > 3) & (arr < 8)): [False False False  True  True  True  True False False False]
Filtered: [4 5 6 7]
Mask ((arr < 3) | (arr > 8)): [ True  True False False False False False False  True  True]
Filtered: [ 1  2  9 10]


In [41]:
# np.where - replacement
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)
result = np.where(arr > 3, 999, arr)
print("np.where(arr > 3, 999, arr):", result)


Array: [1 2 3 4 5]
np.where(arr > 3, 999, arr): [  1   2   3 999 999]


In [42]:
# np.where - finding indices
arr = np.array([1, 2, 3, 4, 5])
indices = np.where(arr > 3)[0]
print("Array:", arr)
print("Indices where arr > 3:", indices)


Array: [1 2 3 4 5]
Indices where arr > 3: [3 4]


In [43]:
# Fancy indexing with arrays
arr = np.array([10, 20, 30, 40, 50])
indices = np.array([0, 2, 4])
print("Array:", arr)
print("Indices:", indices)
print("arr[indices]:", arr[indices])


Array: [10 20 30 40 50]
Indices: [0 2 4]
arr[indices]: [10 30 50]


In [44]:
# 2D fancy indexing
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows = np.array([0, 2])
cols = np.array([1, 2])
print("Array:")
print(arr)
print("arr[rows, cols]:", arr[rows, cols])


Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr[rows, cols]: [2 9]


In [45]:
# Practical example: replace outliers
arr = np.array([1, 2, 3, 100, 5, 200, 6, 7])
mean = arr.mean()
std = arr.std()
print("Array:", arr)
print(f"Mean: {mean:.2f}, Std: {std:.2f}")

# Replace values > mean + 2*std
threshold = mean + 2 * std
arr_clean = np.where(arr > threshold, arr.mean(), arr)
print(f"After replacing outliers (>{threshold:.1f}):", arr_clean)


Array: [  1   2   3 100   5 200   6   7]
Mean: 40.50, Std: 68.01
After replacing outliers (>176.5): [  1.    2.    3.  100.    5.   40.5   6.    7. ]


## 10. Linear Algebra

In [46]:
# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A:")
print(A)
print("B:")
print(B)
print("A @ B (matrix multiplication):")
print(A @ B)
print("np.dot(A, B):")
print(np.dot(A, B))


A:
[[1 2]
 [3 4]]
B:
[[5 6]
 [7 8]]
A @ B (matrix multiplication):
[[19 22]
 [43 50]]
np.dot(A, B):
[[19 22]
 [43 50]]


In [47]:
# Matrix inverse
A = np.array([[1, 2], [3, 4]], dtype=float)
print("A:")
print(A)

A_inv = np.linalg.inv(A)
print("A_inv:")
print(A_inv)
print("A @ A_inv:")
print(A @ A_inv)  # Should be identity


A:
[[1. 2.]
 [3. 4.]]
A_inv:
[[-2.   1. ]
 [ 1.5 -0.5]]
A @ A_inv:
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [48]:
# Determinant
A = np.array([[1, 2], [3, 4]], dtype=float)
det = np.linalg.det(A)
print("A:")
print(A)
print("Determinant:", det)


A:
[[1. 2.]
 [3. 4.]]
Determinant: -2.0000000000000004


In [49]:
# Norm and trace
A = np.array([[1, 2], [3, 4]], dtype=float)
print("A:")
print(A)
print("Frobenius norm:", np.linalg.norm(A))
print("Trace (sum of diagonal):", np.trace(A))


A:
[[1. 2.]
 [3. 4.]]
Frobenius norm: 5.477225575051661
Trace (sum of diagonal): 5.0


In [50]:
# Eigenvalues and eigenvectors
A = np.array([[1, 2], [2, 1]], dtype=float)
eigenvalues, eigenvectors = np.linalg.eig(A)
print("A:")
print(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
print(eigenvectors)


A:
[[1. 2.]
 [2. 1.]]
Eigenvalues: [ 3. -1.]
Eigenvectors:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [51]:
# Solve linear system (Ax = b)
A = np.array([[1, 2], [3, 4]], dtype=float)
b = np.array([5, 11], dtype=float)

x = np.linalg.solve(A, b)
print("A:")
print(A)
print("b:", b)
print("Solution x:", x)
print("Verification (A @ x):", A @ x)


A:
[[1. 2.]
 [3. 4.]]
b: [ 5. 11.]
Solution x: [1. 2.]
Verification (A @ x): [ 5. 11.]


In [52]:
# Singular Value Decomposition
A = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
U, s, Vt = np.linalg.svd(A)
print("A:")
print(A)
print("Singular values:", s)
print("U shape:", U.shape)
print("Vt shape:", Vt.shape)


A:
[[1. 2. 3.]
 [4. 5. 6.]]
Singular values: [9.508032   0.77286964]
U shape: (2, 2)
Vt shape: (3, 3)


## 11. Random Number Generation

In [53]:
# Modern random API with seeding
rng = np.random.default_rng(seed=42)

# Uniform distribution [0, 1)
uniform = rng.uniform(0, 1, size=5)
print("Uniform [0, 1):", uniform)

# Integer random numbers
integers = rng.integers(1, 100, size=5)
print("Integers [1, 100):", integers)


Uniform [0, 1): [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
Integers [1, 100): [53 97 73 76 72]


In [54]:
# Normal distribution
rng = np.random.default_rng(seed=42)
normal = rng.normal(loc=0, scale=1, size=5)
print("Normal(mean=0, std=1):", normal)


Normal(mean=0, std=1): [ 0.30471708 -1.03998411  0.7504512   0.94056472 -1.95103519]


In [55]:
# Common distributions
rng = np.random.default_rng(seed=42)
print("Exponential:", rng.exponential(scale=1, size=3))
print("Poisson:", rng.poisson(lam=3, size=5))
print("Binomial:", rng.binomial(n=10, p=0.5, size=5))


Exponential: [2.4042086  2.33618966 2.384761  ]
Poisson: [3 2 5 1 7]
Binomial: [5 2 3 6 6]


In [56]:
# Shuffle and permutation
rng = np.random.default_rng(seed=42)
arr = np.array([1, 2, 3, 4, 5])
print("Original:", arr)

shuffled = arr.copy()
rng.shuffle(shuffled)
print("After shuffle:", shuffled)

perm = rng.permutation(arr)
print("Permutation:", perm)


Original: [1 2 3 4 5]
After shuffle: [5 3 4 2 1]
Permutation: [4 1 2 3 5]


In [57]:
# Practical example: train/test split
rng = np.random.default_rng(seed=42)
n_samples = 100
n_train = 80

data = np.arange(n_samples)
indices = rng.permutation(n_samples)

train_indices = indices[:n_train]
test_indices = indices[n_train:]

print(f"Total samples: {n_samples}")
print(f"Train indices (first 5): {train_indices[:5]}")
print(f"Test indices (first 5): {test_indices[:5]}")
print(f"Train set size: {len(train_indices)}")
print(f"Test set size: {len(test_indices)}")


Total samples: 100
Train indices (first 5): [59 21 56 18 33]
Test indices (first 5): [49  6 90 11 85]
Train set size: 80
Test set size: 20


## 12. Sorting & Searching

In [58]:
# sort and argsort
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Array:", arr)
print("Sorted:", np.sort(arr))
print("Argsort (indices):", np.argsort(arr))


Array: [3 1 4 1 5 9 2 6]
Sorted: [1 1 2 3 4 5 6 9]
Argsort (indices): [1 3 6 0 2 4 7 5]


In [59]:
# sort in-place
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Original:", arr)
arr.sort()
print("After in-place sort:", arr)


Original: [3 1 4 1 5 9 2 6]
After in-place sort: [1 1 2 3 4 5 6 9]


In [60]:
# Sorting along axis
arr_2d = np.array([[3, 1, 4], [1, 5, 9], [2, 6, 5]])
print("Array:")
print(arr_2d)
print("Sort along axis 0:")
print(np.sort(arr_2d, axis=0))
print("Sort along axis 1:")
print(np.sort(arr_2d, axis=1))


Array:
[[3 1 4]
 [1 5 9]
 [2 6 5]]
Sort along axis 0:
[[1 1 4]
 [2 5 5]
 [3 6 9]]
Sort along axis 1:
[[1 3 4]
 [1 5 9]
 [2 5 6]]


In [61]:
# partition - partial sort
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Array:", arr)
partitioned = np.partition(arr, kth=3)
print("Partition at kth=3:", partitioned)


Array: [3 1 4 1 5 9 2 6]
Partition at kth=3: [1 1 2 3 5 9 4 6]


In [62]:
# searchsorted - find insertion position
arr = np.array([1, 2, 3, 5, 7, 9])
print("Sorted array:", arr)
print("searchsorted(4):", np.searchsorted(arr, 4))
print("searchsorted([0, 5, 10]):", np.searchsorted(arr, [0, 5, 10]))


Sorted array: [1 2 3 5 7 9]
searchsorted(4): 3
searchsorted([0, 5, 10]): [0 3 6]


In [63]:
# nonzero - find non-zero elements
arr = np.array([0, 1, 2, 0, 3, 0])
indices = np.nonzero(arr)[0]
print("Array:", arr)
print("Indices of non-zero elements:", indices)
print("Non-zero values:", arr[indices])


Array: [0 1 2 0 3 0]
Indices of non-zero elements: [1 2 4]
Non-zero values: [1 2 3]


In [64]:
# unique - get unique elements
arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
print("Array:", arr)
unique = np.unique(arr)
print("Unique elements:", unique)

unique, counts = np.unique(arr, return_counts=True)
print("Unique with counts:", list(zip(unique, counts)))


Array: [1 2 2 3 3 3 4 4 4 4]
Unique elements: [1 2 3 4]
Unique with counts: [(np.int64(1), np.int64(1)), (np.int64(2), np.int64(2)), (np.int64(3), np.int64(3)), (np.int64(4), np.int64(4))]


## 13. Performance Tips

In [65]:
# Vectorized vs loops - sum operation
size = 10_000
arr = np.random.default_rng(42).normal(size=size)

# Vectorized (NumPy)
start = time.time()
for _ in range(1000):
    result = np.sum(arr)
numpy_time = time.time() - start

# Loop (Python)
start = time.time()
for _ in range(1000):
    result = sum(arr)
python_time = time.time() - start

print(f"NumPy vectorized: {numpy_time:.4f} seconds")
print(f"Python loop: {python_time:.4f} seconds")
print(f"Speedup: {python_time / numpy_time:.1f}x")


NumPy vectorized: 0.0030 seconds
Python loop: 0.3217 seconds
Speedup: 106.0x


In [66]:
# Pre-allocation vs growing arrays
# Growing array (inefficient)
start = time.time()
arr = np.array([])
for i in range(10000):
    arr = np.append(arr, i)
growing_time = time.time() - start

# Pre-allocated (efficient)
start = time.time()
arr = np.zeros(10000)
for i in range(10000):
    arr[i] = i
preallocated_time = time.time() - start

print(f"Growing array: {growing_time:.4f} seconds")
print(f"Pre-allocated: {preallocated_time:.4f} seconds")
print(f"Speedup: {growing_time / preallocated_time:.1f}x")


Growing array: 0.0223 seconds
Pre-allocated: 0.0007 seconds
Speedup: 34.0x


In [67]:
# In-place operations
arr = np.array([1.0, 2.0, 3.0, 4.0, 5.0])

# Create new array
arr_new = arr * 2
print("Original:", arr)
print("New array (arr * 2):", arr_new)

# In-place modification
arr *= 2
print("After in-place (arr *= 2):", arr)


Original: [1. 2. 3. 4. 5.]
New array (arr * 2): [ 2.  4.  6.  8. 10.]
After in-place (arr *= 2): [ 2.  4.  6.  8. 10.]


In [68]:
# Views vs copies - memory efficiency
arr = np.arange(1_000_000)

# View (shares memory)
view = arr[::2]
print(f"View base is arr: {view.base is arr}")
print(f"View shares data with original")

# Copy (independent)
copy = arr[::2].copy()
print(f"Copy base is arr: {copy.base is arr}")
print(f"Copy is independent")

print(f"Original array size: {arr.nbytes / 1e6:.2f} MB")
print(f"View memory: {view.nbytes / 1e6:.2f} MB (shared)")
print(f"Copy memory: {copy.nbytes / 1e6:.2f} MB (new allocation)")


View base is arr: True
View shares data with original
Copy base is arr: False
Copy is independent
Original array size: 8.00 MB
View memory: 4.00 MB (shared)
Copy memory: 4.00 MB (new allocation)


## 14. Practice Exercises

### Exercise 1: Array Creation and Manipulation
Create a 5x5 matrix where:
- Diagonal elements are 1
- Elements above diagonal are 2
- Elements below diagonal are 3

Then compute the sum of each row and column.

In [69]:
# Exercise 1 Solution
matrix = np.ones((5, 5))
matrix[np.triu_indices_from(matrix, k=1)] = 2
matrix[np.tril_indices_from(matrix, k=-1)] = 3

print("Matrix:")
print(matrix)
print("Row sums:", matrix.sum(axis=1))
print("Column sums:", matrix.sum(axis=0))


Matrix:
[[1. 2. 2. 2. 2.]
 [3. 1. 2. 2. 2.]
 [3. 3. 1. 2. 2.]
 [3. 3. 3. 1. 2.]
 [3. 3. 3. 3. 1.]]
Row sums: [ 9. 10. 11. 12. 13.]
Column sums: [13. 12. 11. 10.  9.]


### Exercise 2: Boolean Masking
Given an array of 20 random numbers between 0 and 100:
- Find values greater than 50
- Replace values between 30 and 70 with 0
- Count how many values are less than 20

In [70]:
# Exercise 2 Solution
rng = np.random.default_rng(42)
arr = rng.integers(0, 101, size=20)

print("Original array:", arr)
print("Values > 50:", arr[arr > 50])

arr_modified = np.where((arr >= 30) & (arr <= 70), 0, arr)
print("After replacing [30, 70]:", arr_modified)

count_less_20 = np.sum(arr < 20)
print(f"Count of values < 20: {count_less_20}")


Original array: [ 9 78 66 44 43 86  8 70 20  9 53 98 74 76 72 79 51 12 84 45]
Values > 50: [78 66 86 70 53 98 74 76 72 79 51 84]
After replacing [30, 70]: [ 9 78  0  0  0 86  8  0 20  9  0 98 74 76 72 79  0 12 84  0]
Count of values < 20: 4


### Exercise 3: Statistics
Generate 1000 random numbers from a normal distribution (mean=100, std=15):
- Compute mean, median, std dev
- Find values within 1 standard deviation of the mean
- Find percentiles (25th, 50th, 75th, 95th)

In [71]:
# Exercise 3 Solution
rng = np.random.default_rng(42)
data = rng.normal(loc=100, scale=15, size=1000)

mean = data.mean()
median = np.median(data)
std = data.std()

print(f"Mean: {mean:.2f}")
print(f"Median: {median:.2f}")
print(f"Std Dev: {std:.2f}")

within_1std = data[(data >= mean - std) & (data <= mean + std)]
print(f"Values within 1 std: {len(within_1std)} ({len(within_1std)/len(data)*100:.1f}%)")

percentiles = np.percentile(data, [25, 50, 75, 95])
print(f"Percentiles [25, 50, 75, 95]: {percentiles}")


Mean: 99.57
Median: 100.09
Std Dev: 14.83
Values within 1 std: 687 (68.7%)
Percentiles [25, 50, 75, 95]: [ 89.55530628 100.09266807 108.84830118 124.24364376]


### Exercise 4: Reshaping and Stacking
Create three 2x3 matrices with different values:
- Stack them vertically to get a 6x3 matrix
- Stack them horizontally to get a 2x9 matrix
- Reshape the first matrix to 1x6 and back to 2x3

In [72]:
# Exercise 4 Solution
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])
C = np.array([[13, 14, 15], [16, 17, 18]])

print("Matrix A:")
print(A)

# Vertical stack
vstack_result = np.vstack([A, B, C])
print("Vstack (6x3):")
print(vstack_result)

# Horizontal stack
hstack_result = np.hstack([A, B, C])
print("Hstack (2x9):")
print(hstack_result)

# Reshape
reshaped = A.reshape(1, 6)
print("A reshaped to (1, 6):", reshaped)
reshaped_back = reshaped.reshape(2, 3)
print("Reshaped back to (2, 3):")
print(reshaped_back)


Matrix A:
[[1 2 3]
 [4 5 6]]
Vstack (6x3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
Hstack (2x9):
[[ 1  2  3  7  8  9 13 14 15]
 [ 4  5  6 10 11 12 16 17 18]]
A reshaped to (1, 6): [[1 2 3 4 5 6]]
Reshaped back to (2, 3):
[[1 2 3]
 [4 5 6]]


### Exercise 5: Linear Algebra Application
Solve the system of equations:
- 2x + 3y = 8
- 4x + y = 10

Then verify the solution.

In [73]:
# Exercise 5 Solution
# System: 2x + 3y = 8
#         4x + y = 10

A = np.array([[2, 3], [4, 1]], dtype=float)
b = np.array([8, 10], dtype=float)

solution = np.linalg.solve(A, b)
x, y = solution

print(f"Solution: x = {x:.2f}, y = {y:.2f}")

# Verify
print("Verification:")
print(f"2*{x:.2f} + 3*{y:.2f} = {2*x + 3*y:.2f} (should be 8)")
print(f"4*{x:.2f} + 1*{y:.2f} = {4*x + y:.2f} (should be 10)")


Solution: x = 2.20, y = 1.20
Verification:
2*2.20 + 3*1.20 = 8.00 (should be 8)
4*2.20 + 1*1.20 = 10.00 (should be 10)
